# use to create a swarm template in Portainer
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      #max_attempts: 3
      window: 20s

x-vol-tz: &v-tz /etc/timezone:/etc/timezone:ro
x-vol-ltime: &v-ltime /etc/localtime:/etc/localtime:ro
x-vol-lgen: &v-lgen /etc/locale.gen:/etc/locale.gen:ro
x-vols: &vols
  - *v-tz
  - *v-ltime
  - *v-lgen

services:
  pyzor-server:
    image: neomediatech/pyzor-server:latest
    hostname: pyzor-server
    <<: *default-opts    
    ports:
      - target: 24441
        published: 24441
        protocol: tcp
        mode: host
    volumes: *vols
    depends_on:
      - redis
  
  nginx:
    image: nginx:1.17-alpine
    #    restart: unless-stopped
    hostname: nginx
    <<: *default-opts
    volumes:
      - *v-tz
      - *v-ltime
      - *v-lgen
      - /tmp:/data:ro
    command: ["nginx", "-g", "daemon off;"]

  redis:
    image: redis:5-alpine
    hostname: redis
    <<: *default-opts    
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_db:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    # according to https://github.com/moby/moby/pull/37701#issuecomment-448014841
    # on docker 19.03 you will be able to set /proc/sys/net/core/somaxconn to 511 instead of default 128
    # like this example below (maybe syntax will change)
    #sysctls:
    #  - net.core.somaxconn=511
    stop_grace_period: 1m


volumes:
  redis_db:
    driver: local
